apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipeline-training.name" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  run_config.yaml: |
    {{- include "pipeline-training.config" . | nindent 4 }}